version: '3.3'

services:

  db:
    build: db
    image: assessment/assessment-db

  feed:
    build: feed
    image: assessment/assessment-api
    ports:
     - "8080:80"
    networks:
      - outwards

networks:
  outwards: