version: '3.3'

services:

  db:
    build: db
    image: assessment/assessment-db

  words:
    build: words
    image: assessment/assessment-api
    deploy:
      replicas: 5

  web:
    build: web
    image: assessment/assessment-web
    ports:
     - "8080:80"
    networks:
      - outwards

networks:
  outwards: