version: '3.3'

services:

  db:
    build: db
    image: assessment/assessment-db

  words:
    build: words
    image: assessment/assessment-api
    ports:
     - "8080:80"
    networks:
      - outwards

networks:
  outwards: