apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: assesment-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: assesment-db
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: assesment-db
spec:
  template:
    metadata:
      labels:
        app: assesment-db
    spec:
      containers:
      - name: db
        image: assesment/assesment-db
        ports:
        - containerPort: 5432
          name: db
---
apiVersion: v1
kind: Service
metadata:
  name: feed
  labels:
    app: feed-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: feed-api
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: feed
  labels:
    app: feed-api
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
      - name: feed
        image: assesment/assesment-api
        ports:
        - containerPort: 8080
          name: api
