CREATE TABLE eurtousd (
  call_id int NOT NULL AUTO_INCREMENT,
  conversion DECIMAL(2,20) NOT NULL,
  inserted_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (call_id)
);
CREATE TABLE usdtoeur (
  call_id int NOT NULL AUTO_INCREMENT,
  conversion DECIMAL(2,20) NOT NULL,
  inserted_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (call_id)
);